name: testcases
publish_to: none
environment:
  sdk: ">=2.1.0 <3.0.0"
dependencies:
  bullseye:
    path: ../bullseye
  # front_end: 0.1.6
  glob: ^1.0.0
  # kernel: 0.3.6
  path: ^1.0.0
  test: ^1.0.0